In [4]:
import torch
# 创建一个5x3的未初始化的Tensor
x=torch.empty(5,3)
print(x)
# 创建一个5x3的随机初始化的Tensor
y=torch.rand(5,3)
print(y)
# 创建一个5x3的long型全0的Tensor
z=torch.zeros(5,3,dtype=torch.long)
print(z)
# 直接根据数据创建:
x = torch.tensor([5.5, 3])
print(x)
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 
print(x.size())
print(x.shape)

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)


tensor([[4.2246e-39, 1.0194e-38, 9.1837e-39],
        [8.4490e-39, 1.0102e-38, 1.0561e-38],
        [9.1837e-39, 9.9183e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39]])
tensor([[0.8481, 0.4516, 0.0117],
        [0.0305, 0.7776, 0.0190],
        [0.8560, 0.2563, 0.4356],
        [0.0891, 0.9137, 0.8449],
        [0.8020, 0.5094, 0.7527]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5945, -1.4122,  0.9841],
        [-0.3648,  0.1630,  0.4328],
        [ 0.1147, -0.4017,  0.4323],
        [-0.3492, -2.5120,  0.9327],
        [ 0.3452, -0.1109,  2.0934]])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 1.4426, -0.9606,  0.9958],
        [-0.3342,  0.9405,  0.4518],
        [ 0.9707, -0.1455,  0.8679],
        [-

In [5]:
y = x[0, :]
# y += 1
print(y)
print(x[0, :]) # 源tensor也被改了


tensor([ 0.5945, -1.4122,  0.9841])
tensor([ 0.5945, -1.4122,  0.9841])


In [6]:
# 用view()来改变Tensor的形状：

y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())
print(z)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[ 0.5945, -1.4122,  0.9841, -0.3648,  0.1630],
        [ 0.4328,  0.1147, -0.4017,  0.4323, -0.3492],
        [-2.5120,  0.9327,  0.3452, -0.1109,  2.0934]])


In [7]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([[ 1.5945, -0.4122,  1.9841],
        [ 0.6352,  1.1630,  1.4328],
        [ 1.1147,  0.5983,  1.4323],
        [ 0.6508, -1.5120,  1.9327],
        [ 1.3452,  0.8891,  3.0934]], device='cuda:0')
tensor([[ 1.5945, -0.4122,  1.9841],
        [ 0.6352,  1.1630,  1.4328],
        [ 1.1147,  0.5983,  1.4323],
        [ 0.6508, -1.5120,  1.9327],
        [ 1.3452,  0.8891,  3.0934]], dtype=torch.float64)
